- .github/workflows/suave-lib-sync.yml
Partially addresses #4. This workflow pulls the Suave.sol libraries from `suave-geth` and mirrors the content for `Suave.sol` and `SuaveForge.sol`. For now, the workflow is triggered manually in the Github actions UI.
> Add github workflow to sync Suave library

- src/Transactions.sol
- test/Transactions.t.sol
This PR fixes the RLP encoding of the legacy transaction type since it only encoded transactions with the to field.
> RLP encode legacy transactions without to address

- .github/workflows/suave-lib-sync.yml
adds a few logs and limits the dispatch type to the one we specify (`suavelib-sync`). 
combined with https://github.com/flashbots/suave-geth/pull/140, this closes https://github.com/flashbots/suave-std/issues/4
> specify dispatch trigger type and add logs to suavelib-sync

- .github/workflows/suave-lib-sync.yml
This PR regenerates the `forge` registry when there is an update of the Suave library since it might include new precompile addresses.
> Regenerate forge registry on suave lib sync

- .gitignore
- tools/forge-gen/foundry.toml
- tools/forge-gen/main.go
I have seen issues with #25 with the imported libraries when we run `forge build` from two different locations, the root and `forge-gen`.
This PR solves those issues by not compiling `Connector.sol` as part of the whole project but in isolation inside `forge-gen`.
> Compile Connector.sol by itself

- src/protocols/Bundle.sol
- test/protocols/Bundle.t.sol
- removes unused `url` param from `BundleObj` struct
- hex-encodes block number for sendBundle request
- returns bytes result from `sendBundle`
> sendBundle tweaks

- src/Transactions.sol
- src/protocols/Bundle.sol
- test/Transactions.t.sol
- test/protocols/Bundle.t.sol
> Add eth_sendBundle protocol

- src/Transactions.sol
The `signTxn` method should be internal, otherwise, the library is not embed inside the Solidity contract.
> Use internal instead of public for signTxn

- .github/workflows/ci.yml
- README.md
- src/protocols/ChatGPT.sol
- test/protocols/ChatGPT.t.sol
This PR introduces an SDK to call ChatGPT from Solidity using the arbitrary http precompile.
> Add ChatGPT protocol

- src/Transactions.sol
Many tx params defined as uint64 are especially susceptible to overflows, such as `value` & `maxFeePerGas`. Some others like `nonce` & `chainId`, while practically insusceptible to overflows, were being needlessly cast to/from `uint64` during RLP decoding/encoding.
Making them all `uint256` solves these problems.
> change uint64 to uint256 in tx structs

- src/Context.sol
- src/forge/ContextConnector.sol
- test/protocols/ChatGPT.t.sol
In `suave-geth`, the address is padded with zeros to the **rigth** but in the mock integration is padded to the left.
> Fix kettle addr padding

- .github/workflows/suave-lib-sync.yml
This PR fixes an issue with the automatic Suave.sol lib sync. If a Suave.sol function that was being used gets updated, the `forge build` command will not work and the PR will fail. Thus, we miss those updates.
So, from now on, if there is a failing Suave.sol update, we will amend the PR and fix the usage of the library.
> Do not build contracts when syncing Suave.sol

- .github/workflows/ci.yml
- src/Logs.sol
- src/Suapp.sol
- test/Logs.t.sol
- test/Other.t.sol
This PR introduces the `suave-std` support to read the logs emitted during off-chain transactions introduced in https://github.com/flashbots/suave-geth/pull/211
> Add support to emit off-chain logs returned in the Suave Transaction

- .github/workflows/suave-lib-sync.yml
Fixes a bug introduced in #58. The gen tool needs `forge` to lint the contracts.
> Fix suave sync forge not found

- src/forge/ConfidentialStore.sol
- src/forge/ConfidentialStoreConnector.sol
- test/Forge.t.sol
The forge integration of the confidential store uses a "connector" contract to bridge precompile calls from `Suave.sol` to the mock contract. Thus, it was not possible to set `address(this)` as an allowed peeker, because when the mock contract checks, it is the address of the "connector" not the one of the caller contract. This PR fixes that issue.
> Fix to allow address(this) in peekers for forge confstore

- src/protocols/EthJsonRPC.sol
- test/protocols/EthJsonRPC.t.sol
Add the JSON-RPC `call()` method to the `EthJsonRPC` protocol.
> Add jsonrpc call() method

- src/forge/Connector.sol
We need both `Vm` and `VmSafe` interfaces from `Vm.sol` in the `Connector.sol` contract but I have been unable to import both without errors when using `suave-std` as an external library.
> Use custom library to mock vmSafe

- src/protocols/EthJsonRPC.sol
- test/protocols/EthJsonRPC.t.sol
I have implemented a `balance()` function in EthJsonRPC to retrieve the balance of the native token. This function is similar to the nonce() function, which retrieves the nonce. I believe having a function to get the native token balance will be beneficial.
This is my first pull request for this repository. Please let me know if there are any additional tasks I should perform.
> Add balance() to utils/EthJsonRPC.sol

- src/protocols/ChatGPT.sol
with overloading function complete , we can use it more flexible, while model and temperature can be passed in parameters
> overload function complete

- src/protocols/EthJsonRPC.sol
There is currently no way to get the error from a JSON RPC call if it fails, which is very annoying for both debugging and contract logic.
This is but a suggestion on how to handle it, alternatives that come up to my mind are:
1. This solution
2. Returning the whole JSON response, not just the `result` item.
3. Adding a `bool success` to the return values, returning `False` and the error as string instead of reverting.
> Revert on Json RPC error

- src/suavelib/Suave.sol
This should fix the most common cases of this error: `context deadline exceeded (Client.Timeout exceeded while awaiting headers)`.
When not present in the `HttpRequest` struct, suave-geth sets the default to 42ms, instead of interpreting the missing value as 0 and setting the default to 5 seconds, like it should.
Adding the param to the `HttpRequest` struct correctly zeroes the value when it's undefined, so suave-geth can interpret the value correctly.
> add timeout param to HttpRequest

- src/Suapp.sol
- test/Forge.t.sol
removes the need to call `require(Suave.isConfidential(), "...")` or write your own modifier, which I've been doing
> add 'confidential' modifier to Suapp

- src/forge/ConfidentialRequest.sol
- test/forge/ConfidentialRequest.t.sol
Realized we can easily trigger the callback of a CCR by forwarding its calldata to another `call`. Simplifies testing a lot.
Come to think of it, I wonder if this would be useful in the actual MEVM...
> add conf request helper for forge

- src/forge/Connector.sol
- test/Fixtures.sol
Do not use the same names as `Forge` interfaces, otherwise, there are issues when a project imports both `suave-std` and `Forge`.
> Do not use same interface names as Forge to avoid collusions

- src/ConfKVS.sol
- test/ConfKVS.t.sol
ConfKVS is a distillation of suave's confidential storage primitives designed to radically simplify the process of creating and retrieving confidential storage records.
It always sets decryptionCondition to 0, so that records are always immediately available, because this is the most common usage, and removing a parameter is always nice.
Using it looks like this:
**1. create a ConfStore**
this should generally be stored by your SUAPP contract's constructor
```solidity
ConfStore cs = ConfStore(addressList, addressList, "my_app_name");
```
**2. set var**
(this value also be stored in your SUAPP contract)
```solidity
ConfRecord memory cr = cs.set("secretKey", abi.encodePacked("secret value"));
```
**3. get var**
```solidity
bytes memory secretKey = cr.get();
assert(keccak256(secretKey) == …
```
> add ConfKVS

- src/Transactions.sol
Using public or external function in a Solidity library forces the library to be externally deployed and linked instead of embedded. From a dev perspective this is super annoying and not that useful.
I don't see a reason why this single function should be public, more so because it is a simple pure function.
> Make decodeSignature internal
